name: 'Hello Reactor Demooo'
description: 'Great someone and record time'

inputs:
  who-to-great: # id of input
    description: 'who to great'
    required: true
    default: 'world'
outputs: 
    time: # id of output
    description: 'The time we greated you'
branding:
  icon: 'shield'
  color: 'blue'

runs:
 using: 'docker'
 main: 'Dockerfile'
 args:
  - ${{input.who-to-great}}
